
### get All
GET http://localhost:5000/company


### get by id
GET http://localhost:5000/company/3

### create
POST http://localhost:5000/company
Content-Type: application/json

{
	"name": "Compañia 3",
	"identifier": "123456789",
	"description": "Compañia de prueba",
	"location": "Colombia"
}

### update
PUT http://localhost:5000/company/1
Content-Type: application/json

{
  "name": "Compañia 3",
  "identifier": "123456789",
  "description": "Compañia de prueba",
  "location": "Colombia"
}
