import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
    return (
        <div>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>About</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo libero provident velit. Omnis dolorum quia beatae quos libero odit reprehenderit nam est quod, et tempore aliquid voluptatem sed molestiae amet.</p>
            </main>
        </div>
    )
}

export default About